# .github/workflows/live_every_6_days.yml

name: Run live.py every 6 days

on:
  schedule:
    - cron: '0 6 1,16 * *'   # 每 6 天的 UTC 6:00 运行一次
  workflow_dispatch:        # 允许手动触发

jobs:
  run-live:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run live.py
        env:
          MY_USERNAME_1: ${{ secrets.n1 }}
          MY_PASSWORD_1: ${{ secrets.p1 }}
          MY_USERNAME_2: ${{ secrets.n2 }}
          MY_PASSWORD_2: ${{ secrets.p2 }}
        run: |
          python live.py
